import ArrowBackRoundedIcon from '@mui/icons-material/ArrowBackRounded'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import ExpandMoreRoundedIcon from '@mui/icons-material/ExpandMoreRounded'
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Chip, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography } from '@mui/material'
import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { EmptyState } from '../../../../shared/ui/components/EmptyState'
import { LoadingScreen } from '../../../../shared/ui/components/LoadingScreen'
import { PageContainer } from '../../../../shared/ui/layout/PageContainer'
import { formatCurrency, formatNumber } from '../../../../shared/utils/formatters'
import { RegisterPaymentDialog } from '../components/RegisterPaymentDialog'
import { useCustomerStatement } from '../hooks/useCustomerStatement'
import type { StatementLot } from '../../domain/entities/AccountStatement'

const monthLabel = (value: string) => new Intl.DateTimeFormat('es-MX', { month: 'long', year: 'numeric' }).format(new Date(`${value.slice(0, 7)}-01T00:00:00`))
const dateLabel = (value: string) => new Intl.DateTimeFormat('es-MX', { dateStyle: 'long' }).format(new Date(`${value}T00:00:00`))
const statusLabel = { PENDING: 'Pendiente', PARTIAL: 'Parcialmente pagada', PAID: 'Pagada' } as const

function LotAccordion({ lot, saleFolio, saleDate }: { lot: StatementLot; saleFolio: string; saleDate: string }) {
  return <Accordion defaultExpanded={lot.outstandingBalance > 0}><AccordionSummary expandIcon={<ExpandMoreRoundedIcon />}><Stack direction={{ xs: 'column', sm: 'row' }} sx={{ width: '100%', justifyContent: 'space-between', pr: 1, gap: 0.5 }}><Typography sx={{ fontWeight: 700 }}>{lot.code}</Typography><Typography color="text.secondary">{lot.outstandingBalance > 0 ? `Saldo pendiente ${formatCurrency(lot.outstandingBalance)}` : 'Liquidado'}</Typography></Stack></AccordionSummary><AccordionDetails><Stack spacing={1.5}><Typography variant="body2" color="text.secondary">Venta {saleFolio} · {dateLabel(saleDate)}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><Typography>Precio acordado: {formatCurrency(lot.agreedPrice)}</Typography><Typography>Enganche: {formatCurrency(lot.downPayment)}</Typography><Typography>Saldo financiado: {formatCurrency(lot.financedAmount)}</Typography><Typography>Total pagado: {formatCurrency(lot.totalPaid)}</Typography><Typography>Saldo pendiente: {formatCurrency(lot.outstandingBalance)}</Typography></Stack><Typography>Superficie: {formatNumber(lot.areaM2, ' m²')}{typeof lot.frontMeters === 'number' && typeof lot.depthMeters === 'number' ? ` · Medidas: ${formatNumber(lot.frontMeters, ' m')} × ${formatNumber(lot.depthMeters, ' m')}` : ''}</Typography>{lot.installments.length ? <Table size="small"><TableHead><TableRow>{['Núm.', 'Mes', 'Importe', 'Pagado', 'Pendiente', 'Estado'].map((header) => <TableCell key={header} sx={{ fontWeight: 700 }}>{header}</TableCell>)}</TableRow></TableHead><TableBody>{lot.installments.map((item) => <TableRow key={item.id}><TableCell>{item.installmentNumber}</TableCell><TableCell>{monthLabel(item.paymentMonth)}</TableCell><TableCell align="right">{formatCurrency(item.amount)}</TableCell><TableCell align="right">{formatCurrency(item.paidAmount)}</TableCell><TableCell align="right">{formatCurrency(item.outstandingAmount)}</TableCell><TableCell><Chip size="small" label={statusLabel[item.status]} variant="outlined" /></TableCell></TableRow>)}</TableBody></Table> : <EmptyState title="Pago total" description="Este lote no tiene mensualidades." />}</Stack></AccordionDetails></Accordion>
}

export function CustomerStatementPage() {
  const navigate = useNavigate(); const id = Number(useParams<{ customerId: string }>().customerId); const query = useCustomerStatement(Number.isFinite(id) ? id : null); const [filter, setFilter] = useState('balance'); const [paymentOpen, setPaymentOpen] = useState(false)
  if (query.isLoading) return <PageContainer><LoadingScreen message="Cargando estado de cuenta..." /></PageContainer>
  if (query.isError || !query.data) return <PageContainer><Alert severity="error">No fue posible cargar el estado de cuenta.</Alert></PageContainer>
  const statement = query.data
  const lots = statement.sales.flatMap((sale) => sale.lots.map((lot) => ({ lot, sale }))).sort((left, right) => left.lot.code.localeCompare(right.lot.code)).filter(({ lot }) => filter === 'all' || (filter === 'balance' ? lot.outstandingBalance > 0 : lot.outstandingBalance === 0))
  const hasPayableInstallments = statement.sales.some((sale) => sale.lots.some((lot) => lot.outstandingBalance > 0 && lot.installments.some((installment) => installment.status !== 'PAID' && installment.outstandingAmount > 0)))
  const accountIsSettled = statement.totals.totalOutstandingBalance <= 0
  return <PageContainer><Stack spacing={2}><Button startIcon={<ArrowBackRoundedIcon />} onClick={() => navigate('/estado-de-cuenta')} sx={{ alignSelf: 'flex-start' }}>Volver al estado de cuenta</Button><Stack direction={{ xs: 'column', sm: 'row' }} sx={{ justifyContent: 'space-between', alignItems: { sm: 'center' }, gap: 1 }}><Box><Typography variant="h4" sx={{ fontWeight: 700 }}>{statement.customer.fullName}</Typography><Typography color="text.secondary">{statement.customer.phone}</Typography></Box>{accountIsSettled ? <Chip label="Cuenta liquidada" color="success" variant="outlined" /> : <Button variant="contained" startIcon={<AddRoundedIcon />} disabled={!hasPayableInstallments} onClick={() => setPaymentOpen(true)}>Registrar pago</Button>}</Stack><Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2, minmax(0, 1fr))', md: 'repeat(6, minmax(0, 1fr))' }, gap: 1.25 }}>{[['Total acordado', statement.totals.totalAgreedAmount], ['Enganche total', statement.totals.totalDownPayment], ['Total financiado', statement.totals.totalFinancedAmount], ['Total pagado', statement.totals.totalPaid], ['Saldo pendiente', statement.totals.totalOutstandingBalance], ['Lotes con saldo', statement.totals.lotsWithBalance]].map(([label, value]) => <Paper key={String(label)} variant="outlined" sx={{ p: 1.5 }}><Typography variant="body2" color="text.secondary">{label}</Typography><Typography sx={{ fontWeight: 700 }}>{typeof value === 'number' && String(label) === 'Lotes con saldo' ? value : formatCurrency(Number(value))}</Typography></Paper>)}</Box><FormControl sx={{ width: 180 }}><InputLabel>Mostrar</InputLabel><Select value={filter} label="Mostrar" onChange={(event) => setFilter(event.target.value)}><MenuItem value="balance">Con saldo</MenuItem><MenuItem value="paid">Liquidados</MenuItem><MenuItem value="all">Todos</MenuItem></Select></FormControl>{lots.length === 0 ? <EmptyState title="Sin lotes para mostrar" description="No hay lotes que coincidan con el filtro seleccionado." /> : lots.map(({ lot, sale }) => <LotAccordion key={lot.saleLotId} lot={lot} saleFolio={sale.folio} saleDate={sale.saleDate} />)}</Stack><RegisterPaymentDialog open={paymentOpen} statement={statement} onClose={() => setPaymentOpen(false)} onSuccess={() => { void query.refetch() }} onOpenReceipt={(paymentId) => navigate(`/pagos/${paymentId}/recibo`)} /></PageContainer>
}
