import SearchRoundedIcon from '@mui/icons-material/SearchRounded'
import VisibilityRoundedIcon from '@mui/icons-material/VisibilityRounded'
import { Alert, Button, InputAdornment, Paper, Stack, Table, TableBody, TableCell, TableHead, TablePagination, TableRow, TextField, Typography } from '@mui/material'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { EmptyState } from '../../../../shared/ui/components/EmptyState'
import { LoadingScreen } from '../../../../shared/ui/components/LoadingScreen'
import { PageContainer } from '../../../../shared/ui/layout/PageContainer'
import { formatCurrency } from '../../../../shared/utils/formatters'
import { useStatementCustomers } from '../hooks/useStatementCustomers'

export function StatementCustomersPage() {
  const navigate = useNavigate(); const [input, setInput] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(0); const [size, setSize] = useState(25)
  useEffect(() => { const timer = window.setTimeout(() => { setSearch(input.trim()); setPage(0) }, 350); return () => window.clearTimeout(timer) }, [input])
  const query = useStatementCustomers({ page, size, search }); const rows = query.data?.content ?? []
  return <PageContainer><Stack spacing={2}><Stack><Typography variant="h4" sx={{ fontWeight: 700 }}>Estado de cuenta</Typography><Typography color="text.secondary">Consulta los lotes, mensualidades y saldos de cada cliente.</Typography></Stack><TextField fullWidth label="Buscar por nombre o teléfono" value={input} onChange={(event) => setInput(event.target.value)} slotProps={{ input: { startAdornment: <InputAdornment position="start"><SearchRoundedIcon /></InputAdornment> } }} />{query.isLoading ? <LoadingScreen message="Cargando clientes con cuenta..." /> : null}{query.isError ? <Alert severity="error">No fue posible cargar los estados de cuenta.</Alert> : null}{!query.isLoading && !query.isError && rows.length === 0 ? <EmptyState title="Sin clientes con ventas" description="Los clientes aparecerán aquí cuando tengan una venta registrada." /> : null}{rows.length > 0 ? <Paper sx={{ overflowX: 'auto' }}><Table sx={{ minWidth: 760 }}><TableHead><TableRow>{['Cliente', 'Lotes con saldo', 'Total acordado', 'Total pagado', 'Saldo pendiente', 'Acción'].map((header) => <TableCell key={header} sx={{ fontWeight: 700 }}>{header}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map((row) => <TableRow key={row.customerId} hover><TableCell><Typography sx={{ fontWeight: 700 }}>{row.customerName}</Typography><Typography variant="body2" color="text.secondary">{row.phone}</Typography></TableCell><TableCell>{row.financedLotCount}</TableCell><TableCell align="right">{formatCurrency(row.totalAgreedAmount)}</TableCell><TableCell align="right">{formatCurrency(row.totalPaid)}</TableCell><TableCell align="right" sx={{ fontWeight: 700 }}>{formatCurrency(row.totalOutstandingBalance)}</TableCell><TableCell><Button size="small" startIcon={<VisibilityRoundedIcon />} onClick={() => navigate(`/estado-de-cuenta/${row.customerId}`)} aria-label={`Ver estado de cuenta de ${row.customerName}`}>Ver estado de cuenta</Button></TableCell></TableRow>)}</TableBody></Table></Paper> : null}<TablePagination component="div" count={query.data?.totalElements ?? 0} page={page} rowsPerPage={size} onPageChange={(_, value) => setPage(value)} onRowsPerPageChange={(event) => { setSize(Number(event.target.value)); setPage(0) }} rowsPerPageOptions={[10, 25, 50]} labelRowsPerPage="Filas por página" labelDisplayedRows={({ from, to, count }) => `${from}-${to} de ${count}`} /></Stack></PageContainer>
}
