export const routePaths = {
  login: '/login',
  dashboard: '/dashboard',
  lots: '/lotes',
  blocks: '/manzanas',
  customers: '/clientes',
  referencePlan: '/plano',
  sales: '/ventas',
  newSale: '/ventas/nueva',
  saleDetail: '/ventas/:id',
  accountStatements: '/estado-de-cuenta',
  customerStatement: '/estado-de-cuenta/:customerId',
  payments: '/pagos',
  reports: '/reportes',
  paymentDetail: '/pagos/:id',
  paymentReceipt: '/pagos/:id/recibo',
}
