CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_full_name_not_blank CHECK (btrim(full_name) <> ''),
    CONSTRAINT ck_users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT ck_users_password_hash_not_blank CHECK (btrim(password_hash) <> '')
);

CREATE TABLE lotifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    address TEXT,
    plan_storage_key VARCHAR(500),
    svg_viewbox VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_lotifications_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lotification_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    area_m2 NUMERIC(12, 2),
    lot_count INTEGER NOT NULL DEFAULT 0,
    reference_color VARCHAR(20),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_blocks_lotification
        FOREIGN KEY (lotification_id)
        REFERENCES lotifications (id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_blocks_lotification_code UNIQUE (lotification_id, code),
    CONSTRAINT ck_blocks_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_blocks_area_non_negative CHECK (area_m2 IS NULL OR area_m2 >= 0),
    CONSTRAINT ck_blocks_lot_count_non_negative CHECK (lot_count >= 0)
);

CREATE TABLE lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id BIGINT NOT NULL,
    lot_number VARCHAR(50) NOT NULL,
    code VARCHAR(100) NOT NULL,
    area_m2 NUMERIC(12, 2),
    front_meters NUMERIC(10, 2),
    depth_meters NUMERIC(10, 2),
    current_price NUMERIC(14, 2),
    status VARCHAR(20) NOT NULL,
    location_reference TEXT,
    notes TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_lots_block
        FOREIGN KEY (block_id)
        REFERENCES blocks (id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_lots_block_lot_number UNIQUE (block_id, lot_number),
    CONSTRAINT uk_lots_code UNIQUE (code),
    CONSTRAINT ck_lots_lot_number_not_blank CHECK (btrim(lot_number) <> ''),
    CONSTRAINT ck_lots_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_lots_area_non_negative CHECK (area_m2 IS NULL OR area_m2 >= 0),
    CONSTRAINT ck_lots_front_non_negative CHECK (front_meters IS NULL OR front_meters >= 0),
    CONSTRAINT ck_lots_depth_non_negative CHECK (depth_meters IS NULL OR depth_meters >= 0),
    CONSTRAINT ck_lots_price_non_negative CHECK (current_price IS NULL OR current_price >= 0),
    CONSTRAINT ck_lots_status CHECK (status IN ('AVAILABLE', 'SOLD', 'BLOCKED'))
);

CREATE TABLE lot_map_shapes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id BIGINT NOT NULL,
    svg_path TEXT NOT NULL,
    label_x NUMERIC(12, 2),
    label_y NUMERIC(12, 2),
    rotation NUMERIC(8, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_lot_map_shapes_lot
        FOREIGN KEY (lot_id)
        REFERENCES lots (id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_lot_map_shapes_lot UNIQUE (lot_id),
    CONSTRAINT ck_lot_map_shapes_svg_path_not_blank CHECK (btrim(svg_path) <> '')
);

CREATE INDEX idx_users_active ON users (is_active);
CREATE INDEX idx_lotifications_active ON lotifications (is_active);
CREATE INDEX idx_blocks_lotification_code ON blocks (lotification_id, code);
CREATE INDEX idx_lots_block_lot_number ON lots (block_id, lot_number);
CREATE INDEX idx_lots_status ON lots (status);
CREATE INDEX idx_lots_code_lot_number ON lots (code, lot_number);
CREATE INDEX idx_lot_map_shapes_lot ON lot_map_shapes (lot_id);
