CREATE TABLE lot_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id BIGINT NOT NULL,
    previous_price NUMERIC(14, 2),
    new_price NUMERIC(14, 2),
    reason TEXT NOT NULL,
    changed_by BIGINT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_lot_price_history_lot
        FOREIGN KEY (lot_id)
        REFERENCES lots (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_lot_price_history_user
        FOREIGN KEY (changed_by)
        REFERENCES users (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_lot_price_history_reason_not_blank CHECK (btrim(reason) <> ''),
    CONSTRAINT ck_lot_price_history_previous_price_non_negative
        CHECK (previous_price IS NULL OR previous_price >= 0),
    CONSTRAINT ck_lot_price_history_new_price_non_negative
        CHECK (new_price IS NULL OR new_price >= 0)
);

CREATE INDEX idx_lot_price_history_lot_changed_at
    ON lot_price_history (lot_id, changed_at DESC, id DESC);
