CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    alternate_phone VARCHAR(20),
    address VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_customers_full_name_not_blank CHECK (btrim(full_name) <> ''),
    CONSTRAINT ck_customers_phone_not_blank CHECK (btrim(phone) <> '')
);

CREATE INDEX idx_customers_full_name ON customers (full_name);
CREATE INDEX idx_customers_phone ON customers (phone);
CREATE INDEX idx_customers_active ON customers (active);
