CREATE SEQUENCE sales_folio_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio VARCHAR(30) NOT NULL,
    customer_id BIGINT NOT NULL,
    sale_date DATE NOT NULL,
    total_agreed_price NUMERIC(14, 2) NOT NULL,
    total_down_payment NUMERIC(14, 2) NOT NULL,
    total_financed_amount NUMERIC(14, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sales_folio UNIQUE (folio),
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sales_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_sales_total_agreed_non_negative CHECK (total_agreed_price >= 0),
    CONSTRAINT ck_sales_total_down_non_negative CHECK (total_down_payment >= 0),
    CONSTRAINT ck_sales_total_financed_non_negative CHECK (total_financed_amount >= 0),
    CONSTRAINT ck_sales_totals_formula CHECK (total_agreed_price = total_down_payment + total_financed_amount),
    CONSTRAINT ck_sales_status CHECK (status IN ('ACTIVE'))
);

CREATE TABLE sale_lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    lot_id BIGINT NOT NULL,
    agreed_price NUMERIC(14, 2) NOT NULL,
    down_payment NUMERIC(14, 2) NOT NULL,
    financed_amount NUMERIC(14, 2) NOT NULL,
    installment_count INTEGER NOT NULL,
    installment_amount NUMERIC(14, 2) NOT NULL,
    first_due_date DATE,
    outstanding_balance NUMERIC(14, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_lots_sale FOREIGN KEY (sale_id) REFERENCES sales (id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_lots_lot FOREIGN KEY (lot_id) REFERENCES lots (id) ON DELETE RESTRICT,
    CONSTRAINT ck_sale_lots_agreed_positive CHECK (agreed_price > 0),
    CONSTRAINT ck_sale_lots_down_non_negative CHECK (down_payment >= 0),
    CONSTRAINT ck_sale_lots_down_not_over_price CHECK (down_payment <= agreed_price),
    CONSTRAINT ck_sale_lots_financed_non_negative CHECK (financed_amount >= 0),
    CONSTRAINT ck_sale_lots_financed_formula CHECK (financed_amount = agreed_price - down_payment),
    CONSTRAINT ck_sale_lots_installment_count_non_negative CHECK (installment_count >= 0),
    CONSTRAINT ck_sale_lots_installment_amount_non_negative CHECK (installment_amount >= 0),
    CONSTRAINT ck_sale_lots_balance_non_negative CHECK (outstanding_balance >= 0),
    CONSTRAINT ck_sale_lots_payment_terms CHECK (
        (financed_amount = 0 AND installment_count = 0 AND installment_amount = 0 AND first_due_date IS NULL AND status = 'PAID')
        OR (financed_amount > 0 AND installment_count > 0 AND installment_amount > 0 AND first_due_date IS NOT NULL AND status = 'ACTIVE')
    ),
    CONSTRAINT ck_sale_lots_status CHECK (status IN ('ACTIVE', 'PAID', 'CANCELLED'))
);

CREATE TABLE sale_installments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_lot_id BIGINT NOT NULL,
    installment_number INTEGER NOT NULL,
    due_date DATE NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    paid_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sale_installments_sale_lot FOREIGN KEY (sale_lot_id) REFERENCES sale_lots (id) ON DELETE RESTRICT,
    CONSTRAINT uk_sale_installments_number UNIQUE (sale_lot_id, installment_number),
    CONSTRAINT ck_sale_installments_number_positive CHECK (installment_number > 0),
    CONSTRAINT ck_sale_installments_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_sale_installments_paid_non_negative CHECK (paid_amount >= 0),
    CONSTRAINT ck_sale_installments_paid_not_over_amount CHECK (paid_amount <= amount),
    CONSTRAINT ck_sale_installments_status CHECK (status IN ('PENDING', 'PARTIAL', 'PAID'))
);

CREATE UNIQUE INDEX uk_sale_lots_active_lot ON sale_lots (lot_id) WHERE status <> 'CANCELLED';
CREATE INDEX idx_sales_customer_date ON sales (customer_id, sale_date DESC);
CREATE INDEX idx_sales_status_date ON sales (status, sale_date DESC);
CREATE INDEX idx_sale_lots_sale ON sale_lots (sale_id);
CREATE INDEX idx_sale_installments_sale_lot_due_date ON sale_installments (sale_lot_id, due_date);
