import ArrowBackRoundedIcon from '@mui/icons-material/ArrowBackRounded'
import ArrowForwardRoundedIcon from '@mui/icons-material/ArrowForwardRounded'
import CheckRoundedIcon from '@mui/icons-material/CheckRounded'
import SearchRoundedIcon from '@mui/icons-material/SearchRounded'
import { Alert, Box, Button, Checkbox, FormControl, InputLabel, MenuItem, Paper, Select, Snackbar, Stack, Step, StepLabel, Stepper, TablePagination, TextField, Typography } from '@mui/material'
import { zodResolver } from '@hookform/resolvers/zod'
import { useFieldArray, useForm, useWatch } from 'react-hook-form'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ApiError } from '../../../../shared/api/apiError'
import { ConfirmDialog } from '../../../../shared/ui/components/ConfirmDialog'
import { PageContainer } from '../../../../shared/ui/layout/PageContainer'
import { formatCurrency, formatNumber } from '../../../../shared/utils/formatters'
import type { SaleCustomerOption, SaleLotOption } from '../../domain/entities/Sale'
import { saleDependencies } from '../../dependencies'
import { MoneyInput } from '../components/MoneyInput'
import { useAvailableLots, useSaleBlocks, useSaleCustomers } from '../hooks/useSaleLookups'
import { saleSchema, type SaleFormValues } from '../schemas/saleSchema'

const steps = ['Cliente', 'Lotes', 'Condiciones de pago', 'Confirmación']
const today = new Date().toISOString().slice(0, 10)

export function NewSalePage() {
  const navigate = useNavigate(); const [step, setStep] = useState(0); const [customerSearch, setCustomerSearch] = useState(''); const [lotSearch, setLotSearch] = useState(''); const [lotPage, setLotPage] = useState(0); const [selectedCustomer, setSelectedCustomer] = useState<SaleCustomerOption | null>(null); const [blockId, setBlockId] = useState<number | undefined>(); const [confirmOpen, setConfirmOpen] = useState(false); const [feedback, setFeedback] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  const form = useForm<SaleFormValues>({ resolver: zodResolver(saleSchema), defaultValues: { customerId: 0, saleDate: today, lots: [] } }); const { control, setValue, trigger, getValues } = form; const fieldArray = useFieldArray({ control, name: 'lots' }); const values = useWatch({ control })
  const customers = useSaleCustomers(customerSearch).data ?? []; const blocks = useSaleBlocks().data ?? []; const lotsQuery = useAvailableLots(undefined, blockId, lotSearch); const lots = useMemo(() => lotsQuery.data ?? [], [lotsQuery.data]); const selectedIds = useMemo(() => new Set((values.lots ?? []).map((lot) => lot.lotId)), [values.lots]); const availableById = useMemo(() => new Map(lots.map((lot) => [lot.id, lot])), [lots]); const sortedLots = useMemo(() => [...lots].sort((left, right) => Number(selectedIds.has(right.id)) - Number(selectedIds.has(left.id))), [lots, selectedIds]); const visibleLots = sortedLots.slice(lotPage * 25, lotPage * 25 + 25)
  function changeLotSearch(search: string) { setLotSearch(search); setLotPage(0) }
  function changeBlock(block: number | undefined) { setBlockId(block); setLotPage(0) }
  function selectCustomer(customer: SaleCustomerOption) { setSelectedCustomer(customer); setValue('customerId', customer.id, { shouldValidate: true }); setCustomerSearch('') }
  function toggleLot(lot: SaleLotOption) { const index = fieldArray.fields.findIndex((item) => item.lotId === lot.id); if (index >= 0) fieldArray.remove(index); else fieldArray.append({ lotId: lot.id, agreedPrice: lot.price ?? 0, downPayment: 0, installmentCount: 12 }) }
  async function next() { const valid = step === 0 ? await trigger('customerId') : step === 1 ? fieldArray.fields.length > 0 : await trigger(); if (valid) setStep((value) => Math.min(value + 1, 3)) }
  async function submit() { if (!(await trigger())) return; setSaving(true); try { const saved = await saleDependencies.createSaleUseCase.execute(getValues()); navigate(`/ventas/${saved.id}`) } catch (error) { setFeedback(error instanceof ApiError ? error.message : 'No fue posible registrar la venta.'); setStep(1) } finally { setSaving(false); setConfirmOpen(false) } }
  const total = (values.lots ?? []).reduce((sum, lot) => sum + (lot.agreedPrice ?? 0), 0); const down = (values.lots ?? []).reduce((sum, lot) => sum + (lot.downPayment ?? 0), 0); const financed = total - down

  return <PageContainer><Stack spacing={2.5}><Stack direction={{ xs: 'column', sm: 'row' }} sx={{ justifyContent: 'space-between', alignItems: { sm: 'center' } }}><Box><Typography variant="h4" sx={{ fontWeight: 700 }}>Nueva venta</Typography><Typography color="text.secondary">Registra una operación para uno o varios lotes.</Typography></Box><Button startIcon={<ArrowBackRoundedIcon />} onClick={() => navigate('/ventas')}>Historial de ventas</Button></Stack><Stepper activeStep={step} alternativeLabel>{steps.map((label) => <Step key={label}><StepLabel>{label}</StepLabel></Step>)}</Stepper>
    {step === 0 ? <Paper sx={{ p: 2.5 }}><Stack spacing={2}>{selectedCustomer ? <Paper variant="outlined" sx={{ p: 1.5, bgcolor: 'background.paper' }}><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center', gap: 2 }}><Box><Typography sx={{ fontWeight: 700 }}>{selectedCustomer.fullName}</Typography><Typography variant="body2" color="text.secondary">{selectedCustomer.phone}{selectedCustomer.address ? ` · ${selectedCustomer.address}` : ''}</Typography></Box><Button size="small" onClick={() => { setSelectedCustomer(null); setValue('customerId', 0) }}>Cambiar cliente</Button></Stack></Paper> : <><TextField label="Buscar cliente activo" placeholder="Nombre o teléfono" value={customerSearch} onChange={(event) => setCustomerSearch(event.target.value)} slotProps={{ input: { startAdornment: <SearchRoundedIcon color="action" sx={{ mr: 1 }} /> } }} />{customers.map((customer) => <Button key={customer.id} variant="outlined" onClick={() => selectCustomer(customer)} sx={{ justifyContent: 'flex-start', textAlign: 'left', color: 'text.primary' }}><Box><Typography sx={{ fontWeight: 700 }}>{customer.fullName}</Typography><Typography variant="body2">{customer.phone}{customer.address ? ` · ${customer.address}` : ''}</Typography></Box></Button>)}<Typography color="text.secondary">Busca al menos dos caracteres para consultar clientes activos.</Typography></>}</Stack></Paper> : null}
    {step === 1 ? <Paper sx={{ p: 2.5 }}><Stack spacing={2}><Stack direction={{ xs: 'column', md: 'row' }} spacing={1.5}><TextField fullWidth label="Buscar por código o número" value={lotSearch} onChange={(event) => changeLotSearch(event.target.value)} /><FormControl sx={{ minWidth: 200 }}><InputLabel id="sale-block">Manzana</InputLabel><Select labelId="sale-block" label="Manzana" value={blockId ?? ''} onChange={(event) => changeBlock(event.target.value ? Number(event.target.value) : undefined)}><MenuItem value="">Todas</MenuItem>{blocks.map((block) => <MenuItem key={block.id} value={block.id}>{block.code}</MenuItem>)}</Select></FormControl></Stack><Typography sx={{ fontWeight: 700 }}>{selectedIds.size} {selectedIds.size === 1 ? 'lote seleccionado' : 'lotes seleccionados'}</Typography>{lots.length === 0 ? <Typography color="text.secondary">No hay lotes disponibles con los filtros actuales.</Typography> : <>{visibleLots.map((lot) => { const selected = selectedIds.has(lot.id); return <Button key={lot.id} variant="outlined" onClick={() => toggleLot(lot)} sx={{ justifyContent: 'flex-start', textAlign: 'left', color: 'text.primary', borderColor: selected ? 'primary.main' : 'divider', bgcolor: selected ? 'action.selected' : 'background.paper' }}><Checkbox checked={selected} color="primary" tabIndex={-1} /><Box><Typography sx={{ fontWeight: 700 }}>{lot.code}</Typography><Typography variant="body2">{lot.blockCode} · {lot.lotNumber} · {formatNumber(lot.areaM2 ?? null, ' m²')} · {formatNumber(lot.frontMeters ?? null, ' m')} × {formatNumber(lot.depthMeters ?? null, ' m')} · {formatCurrency(lot.price ?? null)}</Typography></Box></Button> })}<TablePagination component="div" count={lots.length} page={lotPage} onPageChange={(_, page) => setLotPage(page)} rowsPerPage={25} rowsPerPageOptions={[25]} labelRowsPerPage="Lotes por página" labelDisplayedRows={({ from, to, count }) => `${from}-${to} de ${count}`} /></>}</Stack></Paper> : null}
    {step === 2 ? <Stack spacing={1.5}>{fieldArray.fields.map((field, index) => { const lot = availableById.get(field.lotId); const condition = values.lots?.[index]; const agreedPrice = condition?.agreedPrice ?? 0; const downPayment = condition?.downPayment ?? 0; const balance = agreedPrice - downPayment; const installment = balance > 0 && (condition?.installmentCount ?? 0) > 0 ? balance / (condition?.installmentCount ?? 1) : 0; return <Paper key={field.id} sx={{ p: 2 }}><Stack spacing={1.5}><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}><Typography sx={{ fontWeight: 800 }}>{lot?.code ?? `Lote ${field.lotId}`}</Typography><Typography variant="body2" color="text.secondary">Precio actual: {formatCurrency(lot?.price ?? null)}</Typography></Stack><Stack direction={{ xs: 'column', md: 'row' }} spacing={1.5}><MoneyInput control={control} name={`lots.${index}.agreedPrice`} label="Precio acordado" /><MoneyInput control={control} name={`lots.${index}.downPayment`} label="Enganche" /><TextField fullWidth type="number" label="Mensualidades" {...form.register(`lots.${index}.installmentCount`, { valueAsNumber: true })} /></Stack>{balance <= 0 ? <Alert severity="info">Pago total</Alert> : <Stack spacing={0.5}><Typography>Saldo a financiar: <strong>{formatCurrency(Math.max(balance, 0))}</strong></Typography><Typography>Mensualidad aproximada: <strong>{formatCurrency(installment)}</strong></Typography><Typography color="text.secondary"></Typography></Stack>}</Stack></Paper> })}<Typography variant="caption" color="text.secondary">Cada mensualidad corresponde a un mes y no tiene una fecha límite de pago.</Typography></Stack> : null}
    {step === 3 ? <Paper sx={{ p: 2.5 }}><Stack spacing={1}><Typography variant="h6">Resumen de la venta</Typography><Typography>Cliente: <strong>{selectedCustomer?.fullName}</strong></Typography><Typography>Fecha de venta: {values.saleDate}</Typography><Typography>Lotes seleccionados: {selectedIds.size}</Typography><Typography>Total acordado: <strong>{formatCurrency(total)}</strong></Typography><Typography>Enganche total: <strong>{formatCurrency(down)}</strong></Typography><Typography>Total financiado: <strong>{formatCurrency(Math.max(financed, 0))}</strong></Typography>{values.lots?.map((lot) => <Typography key={lot.lotId ?? 0} variant="body2">{availableById.get(lot.lotId ?? 0)?.code ?? lot.lotId}: {formatCurrency(lot.agreedPrice ?? 0)} · enganche {formatCurrency(lot.downPayment ?? 0)}</Typography>)}<Typography color="text.secondary" sx={{ mt: 1 }}>Las mensualidades no tienen una fecha límite específica.</Typography></Stack></Paper> : null}
    <Stack direction="row" sx={{ justifyContent: 'space-between' }}><Button disabled={step === 0} startIcon={<ArrowBackRoundedIcon />} onClick={() => setStep((value) => value - 1)}>Volver</Button>{step < 3 ? <Button variant="contained" disabled={step === 1 && fieldArray.fields.length === 0} endIcon={<ArrowForwardRoundedIcon />} onClick={() => void next()}>Continuar</Button> : <Button variant="contained" startIcon={<CheckRoundedIcon />} onClick={() => setConfirmOpen(true)}>Confirmar venta</Button>}</Stack></Stack><ConfirmDialog open={confirmOpen} title="Confirmar venta" description="Al confirmar, los lotes seleccionados cambiarán a vendidos y se generará su plan mensual. Esta operación no podrá editarse directamente." confirmLabel="Confirmar venta" pending={saving} onClose={() => setConfirmOpen(false)} onConfirm={() => void submit()} /><Snackbar open={feedback !== null} autoHideDuration={6000} onClose={() => setFeedback(null)}><Alert severity="error" sx={{ width: '100%' }}>{feedback}</Alert></Snackbar></PageContainer>
}
